name: Print Hello File

on:
  push:
    branches:
      - master

jobs:
  print_hello_txt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read hello.txt content
        run: |
          echo "Reading hello.txt content..."
          cat hello.txt